### ISSUE TITLE
Could not resolve "fwidgets/ui"

### ISSUE THREAD

**Issue by bonsak** [fwextensions/fwidgets#1]
Hi
This project looks super useful! Thanks!
But i get an error when i try to build it after i run npm install:
```
info Typechecking...
error TypeScript error

    src/main.ts:1:26 - error TS2307: Cannot find module 'fwidgets' or its corresponding type declarations.
    1 import { fwidgets } from "fwidgets";
    src/main.ts:31:34 - error TS7031: Binding element 'input' implicitly has an 'any' type.
    31 export default fwidgets(async ({ input, output, ui }) => {
    src/main.ts:31:41 - error TS7031: Binding element 'output' implicitly has an 'any' type.
    31 export default fwidgets(async ({ input, output, ui }) => {
    src/main.ts:31:49 - error TS7031: Binding element 'ui' implicitly has an 'any' type.
    31 export default fwidgets(async ({ input, output, ui }) => {
    src/ui.tsx:1:39 - error TS2307: Cannot find module 'fwidgets/ui' or its corresponding type declarations.
    1 export { FwidgetsUI as default } from "fwidgets/ui";
```
If i comment out the typechecking in tsconfig i'm left with this error.
```
info Building...
error esbuild error
    Build failed with 1 error:
    src/ui.tsx:1:38: ERROR: Could not resolve "fwidgets/ui"
```

**Comment by fwextensions** [comment]
Sorry for the slow response!  

Hmm, you're right.  I just tried creating a fresh plugin with this command `npm create fwidgets@latest` (I'm assuming that's what you did), and then `npm run build` generates similar errors.  Looking into it...

**Comment by fwextensions** [comment]
Okay, so I confused myself while testing within the monorepo, and made two dumb mistakes.  One was not actually including the `fwidgets` package in the `package.json` template file, which worked while in the monorepo, since the package could be found locally.  So running `npm i fwidgets` in your plugin directory will fix that.

🙄

The other is that the packaging process wasn't picking up an index file needed to make the import in `main.ts` work.  So if you change the first line in `main.ts` to:

```ts
import { fwidgets } from "fwidgets/main";
```

that will fix the import statement.  After that, the build should work.  

Thanks for letting me know about the error!

**Comment by fwextensions** [comment]
I've pushed a new version of the package which should fix the issue you saw.  If you run this again:

```sh
npm create fwidgets@latest
```

It should ask to install version `0.0.6`.  Running `npm install` and then `npm run build` should correctly build the sample code, which you can then modify.

Please let me know if you see any other issues or have suggestions!
